#!/bin/sh -x
if [ "$1" = "" -o ! -d tlib/"$1" ]; then
    echo "Usage:  Makeall unix32|unix64"
    exit 99
else
    if [ "$1" = "unix32" ]; then
	sys="unix32"
	SYS="UNIX32"
    fi
    if [ "$1" = "unix64" ]; then
	sys="unix64"
	SYS="UNIX64"
    fi
fi
if [ "$SYS" = "" ]; then
    echo "Usage:  Makeall unix32|unix64"
    exit 99
fi
echo "====="
cd cmd
make SYS=${SYS}
cp tpc ../usr/local/bin
cp lib/as.${SYS}.sh ../usr/local/lib/tplus/as
cp lib/cc.${SYS}.sh ../usr/local/lib/tplus/cc
cp lib/ld.${SYS}.sh ../usr/local/lib/tplus/ld
cd ..
echo "====="
cd scanparse
make SYS=${SYS}
cp scanparse.x ../usr/local/lib/tplus
cd ..
echo "====="
cd semantic.1
make SYS=${SYS}
cp semantic1.x ../usr/local/lib/tplus
cd ..
echo "====="
cd semantic.2
make SYS=${SYS}
cp semantic2.x ../usr/local/lib/tplus
cd ..
echo "====="
cd t+toc
make SYS=${SYS}
cp t+toc.x ../usr/local/lib/tplus
cp *.mdp ../usr/local/lib/tplus
for i in UNIX32 UNIX64 
do
    cp cinterface.h.$i ../usr/local/include/tplus/$i/cinterface.h 
done
cd ..
echo "====="
cd tlib/${sys}
make sys=${sys} SYS=${SYS}
cp *.a ../../usr/local/lib/tplus
cd ../..
echo "====="
cd tssl
make SYS=${SYS}
cp ssl.x ../usr/local/lib/tplus
cp tssl.sh ../usr/local/bin/tssl
cd ..
echo "====="
